name: Test
on:
  push:
  pull_request:
jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10.14
      - uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.6.1
      - run: |
          poetry install --with dev
          pytest --cov=lingoqa_dataset --cov-report=xml
        shell: bash
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          flags: pytest # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: hakuturu583/lingoqa_dataset
