name: Test
on:
  push:
  pull_request:
jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - uses: atu4403/poetry-setup-multi-platform@v1
      - run: |
          poetry install
          poetry run pytest
        shell: bash